# Generated by Django 2.0.1 on 2018-01-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Skill', max_length=150, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
